### ISSUE TITLE
User can search for albums

### ISSUE THREAD

**Issue by mariannecuevas** [mariannecuevas/final-project#1]
## ⚙️ Feature

> ##### Users can search for an artist's albums

## 📐 Functionality

> ##### Users will be able to search for an artist of their liking and that artist's albums will appear on the page.

## 🖼️ Wireframes

> ##### ![image](https://github.com/mariannecuevas/final-project/assets/117552789/884cd8ba-fc61-48f3-a30c-37123dafa89a)
> ##### ![image](https://github.com/mariannecuevas/final-project/assets/117552789/2464a970-dfd9-49c3-b5d2-3c9fb0daca56)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Go onto Spotify for Developers, create an app, and get the Client ID and Secret
  - [x] Add this info to the env file
- [x] Update `server.js` to handle requests from Spotify API and send it back to the client
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update the `app.js` file
  - [x] Fetch the API Access Token
- [x] Create a component to handle the search bar.
- [x] Create a component to handle the albums list.
- [x] Create a component for the search page
  - [x] Fetch the search input endpoint to be able to search artists
- [x] Change the styling to your liking

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
