### ISSUE TITLE
User can bookmark albums

### ISSUE THREAD

**Issue by mariannecuevas** [mariannecuevas/final-project#11]
## ⚙️ Feature

> ##### User can bookmark albums.

## 📐 Functionality

> ##### Users will be able to click on an icon that will allow them to bookmark albums they would like to go back to.

## 🖼️ Wireframes

> #####

![image](https://github.com/mariannecuevas/final-project/assets/117552789/58c35fe8-e545-4e96-96cd-f201047b1de6)
![image](https://github.com/mariannecuevas/final-project/assets/117552789/9b4ba0e7-f7a1-4381-9093-c336f7c558c2)
![image](https://github.com/mariannecuevas/final-project/assets/117552789/fc2a9267-c488-488e-99be-2a565142309f)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to have the correct time for "createdAt" and "updatedAt"

### ☁️ Server Tasks

- [x] Update `server.js`
  - [x] Define API endpoints for bookmarks. Create routes for creating and retrieving bookmarks.
  - [x] Write SQL queries for database interactions (creating and retrieving bookmarks).
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update the AlbumList component
  - [x] Add a bookmark icon
  - [x] Fetch the bookmarks
  - [x] Communicate with the server to either post or delete bookmarks

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
