### ISSUE TITLE
User can view bookmarks

### ISSUE THREAD

**Issue by mariannecuevas** [mariannecuevas/final-project#13]
## ⚙️ Feature

> ##### User can view their bookmarks.

## 📐 Functionality

> ##### Users will be able to click on a bookmarks link in the drawer menu and this link will show all the user's bookmarked albums.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/mariannecuevas/final-project/assets/117552789/30e64af6-c401-4075-9372-f612ae2e1666)
![image](https://github.com/mariannecuevas/final-project/assets/117552789/3badcb64-78c2-463d-9b70-417f5353fec7)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component for the bookmarks page.
  - [x] Fetch the bookmarked albums
  - [x] Add a function to allow users to remove a bookmark.
    - [x] A modal for asking the user if they would like to remove a bookmark.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
