### ISSUE TITLE
User can register an account

### ISSUE THREAD

**Issue by mariannecuevas** [mariannecuevas/final-project#15]
## ⚙️ Feature

> ##### User can register for an account.

## 📐 Functionality

> ##### Users will be able to register for a music diary account to keep track of their album reviews and bookmarks.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/mariannecuevas/final-project/assets/117552789/51485889-632b-4d68-aa90-1e92d5f5e7f4)
![image](https://github.com/mariannecuevas/final-project/assets/117552789/bc751779-958d-41d8-ac91-6bf800ecdec2)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include userId

### ☁️ Server Tasks

- [x] Update `server.js` 
  - [x] Create a sign-up route that handles requests for user registration
    - [x] Handle the authentication (give client token; hashedpassword)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for the user registration page
  - [x] Add a form for users to add their user info for registration

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
