### ISSUE TITLE
Users can sign in and access their reviews/bookmarks

### ISSUE THREAD

**Issue by mariannecuevas** [mariannecuevas/final-project#17]
## ⚙️ Feature

> ##### Users can sign in and access their entries.

## 📐 Functionality

> ##### Users will be able to log into their music diary account and see their album reviews and bookmarks.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/mariannecuevas/final-project/assets/117552789/9f4dac9f-7992-4037-892a-19a0ae52924c)
![image](https://github.com/mariannecuevas/final-project/assets/117552789/90b4e32f-3bf1-469a-a016-d40d4c9688f9)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql`
  - [x] Fix any date issues

### ☁️ Server Tasks

- [x] Update `server.js` to:
  - [x] Accept credentials (username and password) from a client and respond with a JSON Web Token - Authentication
  - [x] Include an authorization middleware for users - Authorization
- [x] Test with HTTPie
- [x] Make sure users are only allowed to see their own reviews/bookmarks
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Have the sign-in/register page be the homepage
- [x] Update the Register component to show messages for unsuccessful registration/sign-in attempts

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
