### ISSUE TITLE
User can rate and review albums

### ISSUE THREAD

**Issue by mariannecuevas** [mariannecuevas/final-project#3]
## ⚙️ Feature

> ##### User can rate and review albums.

## 📐 Functionality

> ##### Users will be able to click on any album of their liking and submit a review of the album.

## 🖼️ Wireframes

> ##### ![image](https://github.com/mariannecuevas/final-project/assets/117552789/32845e3a-8c00-4d04-b1e4-ea09de98e94a)
> ##### ![image](https://github.com/mariannecuevas/final-project/assets/117552789/70968a24-910a-4f92-9eb5-a987584ea9a6)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` with the desired tables and fields
  - [x] Make sure the to remove any unnecessary fields

### ☁️ Server Tasks

- [x] Update `server.js`
  - [x] Define API endpoints for album reviews. Create routes for creating and retrieving reviews.
    - [x] Write SQL queries for database interactions (creating new reviews and retrieving reviews.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] In the SearchPage component
  - [x] Create an onClick event for selecting an Album
    - [x] Handle this onClick event inside the AlbumList component to have the correct album selected
        - [x] Make the cursor is pointer when the album is hovered
  - [x] Create a rate and review modal inside SearchPage that appears once an album is clicked
    - [x] Add the necessary user interface components
    - [x] Implement functions for making API requests to the server for creating and retrieving album reviews.
- [x] Fix styling

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
