### ISSUE TITLE
User can view reviewed albums

### ISSUE THREAD

**Issue by mariannecuevas** [mariannecuevas/final-project#5]
## ⚙️ Feature

> ##### Users can view their reviewed albums.

## 📐 Functionality

> ##### Users will be able to click on a link from a menu that allows them to view all of their reviewed albums.

## 🖼️ Wireframes

![image](https://github.com/mariannecuevas/final-project/assets/117552789/cb202a21-0374-48b2-ac90-f8e42a44640e)
![image](https://github.com/mariannecuevas/final-project/assets/117552789/8f777e27-3f06-40c3-96d7-7fd9054c14c0)
![image](https://github.com/mariannecuevas/final-project/assets/117552789/4742300a-798f-4dae-a4f8-0afba3a9e757)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
### ☁️ Server Tasks

- [x] Update `server.js` to send a GET request for the reviewed albums in the database.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create an app drawer component that can be toggled open and closed for the menu
  - [x]  Add links for the homepage (search page) and the album reviews page
- [x] Create a component for the album reviews page.
  - [x] GET request to grab the data from the database

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
