### ISSUE TITLE
User can edit album reviews

### ISSUE THREAD

**Issue by mariannecuevas** [mariannecuevas/final-project#7]
## ⚙️ Feature

> ##### User can edit their album reviews.

## 📐 Functionality

> ##### Users will be able to edit any album reviews they have submitted.

## 🖼️ Wireframes

![image](https://github.com/mariannecuevas/final-project/assets/117552789/fb8b3647-571d-4430-af3a-86bafb6759e8)
![image](https://github.com/mariannecuevas/final-project/assets/117552789/25eca484-653c-493c-9385-ec639e5e4c4f)
![image](https://github.com/mariannecuevas/final-project/assets/117552789/03835f18-f665-4edf-92c7-a913579b8b39)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to include a PATCH request to update any album review entry. NOTE: PUT is for updating everything. PATCH is for partial updates.
  - [x] use UPDATE, SET, WHERE
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update the AlbumReviewsPage component to have an editing icon
  - [x] When the edit icon is clicked, add a modal to update the review

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
