### ISSUE TITLE
User can delete reviews

### ISSUE THREAD

**Issue by mariannecuevas** [mariannecuevas/final-project#8]
## ⚙️ Feature

> ##### User can delete their album reviews.

## 📐 Functionality

> ##### Users will be able to click on an icon that will give them the option to delete their review.

## 🖼️ Wireframes

![image](https://github.com/mariannecuevas/final-project/assets/117552789/bb117e0a-6d80-4426-81d7-555e88e48b19)
![image](https://github.com/mariannecuevas/final-project/assets/117552789/17b5f181-bd17-4621-a6b0-e3eb420fe7ea)
![image](https://github.com/mariannecuevas/final-project/assets/117552789/e39b86b0-e44b-4da6-ac76-391bb0fe4f97)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to include a DELETE request to delete any album review entry.
  - [x] DELETE, FROM, WHERE
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update the AlbumReviewsPage component to have a trash/delete icon
  - [x] When the icon is clicked, add a modal that gives the option to delete the review or cancel.

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
